//! Typed IR → C. Every array or view is two C variables, `name_p` and `name_n`, so a parameter
//! can carry `restrict` on the pointer and the C compiler sees what the language already knows:
//! nothing aliases. Blocks and `if` with values use GNU statement expressions, which gcc and
//! clang — the two compilers this targets — both accept.

use std::fmt::Write;

use crate::ast::UnOp;
use crate::ir::*;

pub struct Options {
    /// Emit a bounds check on every index. Off for measurement.
    pub checked: bool,
}

enum CVal {
    Scalar(String),
    Arr(String, String),
}

impl CVal {
    fn scalar(self) -> String {
        match self { CVal::Scalar(s) => s, CVal::Arr(p, _) => p }
    }
}

struct Emitter<'a> {
    m: &'a Module,
    f: Option<&'a Func>,
    opts: &'a Options,
    out: String,
    indent: usize,
    tmp: usize,
}

pub fn emit(m: &Module, opts: &Options) -> String {
    let mut e = Emitter { m, f: None, opts, out: String::new(), indent: 0, tmp: 0 };
    e.prelude();
    for f in &m.funcs {
        e.f = Some(f);
        e.prototype(f);
        e.out.push_str(";\n");
    }
    e.out.push('\n');
    for f in &m.funcs {
        e.f = Some(f);
        e.func(f);
    }
    e.out.push_str("int main(void) { nt_main(); return 0; }\n");
    e.out
}

fn c_ty(t: &Ty) -> &'static str {
    match t {
        Ty::I64 => "int64_t",
        Ty::F64 => "double",
        Ty::Bool => "bool",
        Ty::Unit => "void",
        Ty::Array(e, _) | Ty::Slice(e, _, _) => c_ty(e),
    }
}

impl<'a> Emitter<'a> {
    fn prelude(&mut self) {
        self.out.push_str(r#"// generated by neant (bootstrap compiler)
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>

static void *nt_alloc(int64_t n, size_t sz) {
    if (n < 0) { fprintf(stderr, "negative array length %lld\n", (long long)n); exit(101); }
    void *p = malloc(n == 0 ? 1 : (size_t)n * sz);
    if (!p) { fprintf(stderr, "out of memory\n"); exit(101); }
    return p;
}
"#);
        if self.opts.checked {
            self.out.push_str(r#"static inline int64_t nt_idx(int64_t i, int64_t n, int line) {
    if ((uint64_t)i >= (uint64_t)n) {
        fprintf(stderr, "index %lld out of bounds for length %lld (line %d)\n", (long long)i, (long long)n, line);
        exit(101);
    }
    return i;
}
"#);
        } else {
            self.out.push_str("#define nt_idx(i, n, line) (i)\n");
        }
        self.out.push_str(r#"static void nt_println_i64(int64_t v) { printf("%lld\n", (long long)v); }
static void nt_println_bool(bool v) { puts(v ? "true" : "false"); }
static void nt_println_f64(double v) {
    // as Rust prints: shortest digits that round-trip, never an exponent, `.0` on integral values
    char buf[400];
    if (v != v) { puts("NaN"); return; }
    if (v == 1.0 / 0.0) { puts("inf"); return; }
    if (v == -1.0 / 0.0) { puts("-inf"); return; }
    int prec = 0;
    for (; prec < 17; prec++) {
        snprintf(buf, sizeof buf, "%.*e", prec, v);
        if (strtod(buf, NULL) == v) break;
    }
    int exp10 = atoi(strchr(buf, 'e') + 1);
    int decimals = prec - exp10;
    if (decimals < 0) decimals = 0;
    snprintf(buf, sizeof buf, "%.*f", decimals, v);
    if (!strchr(buf, '.')) strcat(buf, ".0");
    puts(buf);
}

"#);
    }

    fn local_name(&self, id: LocalId) -> String {
        let l = &self.f.unwrap().locals[id];
        // compiler-made locals are `base#n`; the id suffix already makes every name unique
        format!("{}_{}", l.name.replace('#', "_"), id)
    }

    fn prototype(&mut self, f: &Func) {
        let ret = c_ty(&f.ret);
        let _ = write!(self.out, "static {ret} nt_{}(", f.name);
        if f.params.is_empty() {
            self.out.push_str("void");
        }
        for (i, &p) in f.params.iter().enumerate() {
            if i > 0 { self.out.push_str(", "); }
            let l = &f.locals[p];
            let nm = self.local_name(p);
            match &l.ty {
                Ty::Slice(e, m, _) => {
                    let cst = if *m { "" } else { "const " };
                    let _ = write!(self.out, "{cst}{} *restrict {nm}_p, int64_t {nm}_n", c_ty(e));
                }
                t => { let _ = write!(self.out, "{} {nm}", c_ty(t)); }
            }
        }
        self.out.push(')');
    }

    fn func(&mut self, f: &Func) {
        self.prototype(f);
        self.out.push_str(" {\n");
        self.indent = 1;
        self.tmp = 0;
        let ret_scalar = f.ret != Ty::Unit;
        self.block_body(&f.body, if ret_scalar { Target::Return } else { Target::Discard });
        self.out.push_str("}\n\n");
    }

    fn line(&mut self, s: &str) {
        for _ in 0..self.indent { self.out.push_str("    "); }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn fresh(&mut self, base: &str) -> String {
        self.tmp += 1;
        format!("nt_{base}{}", self.tmp)
    }

    fn block_body(&mut self, b: &Block, target: Target) {
        for s in &b.stmts {
            self.stmt(s);
        }
        if let Some(t) = &b.tail {
            match target {
                Target::Return => {
                    let v = self.expr(t).scalar();
                    self.line(&format!("return {v};"));
                }
                Target::Assign(ref name) => {
                    let v = self.expr(t).scalar();
                    self.line(&format!("{name} = {v};"));
                }
                Target::Discard => {
                    self.expr_stmt(t);
                }
            }
        }
    }

    fn stmt(&mut self, s: &Stmt) {
        match s {
            Stmt::Let(id, e) => {
                let nm = self.local_name(*id);
                let ty = self.f.unwrap().locals[*id].ty.clone();
                match self.expr(e) {
                    CVal::Scalar(v) => self.line(&format!("{} {nm} = {v};", c_ty(&ty))),
                    CVal::Arr(p, n) => {
                        let cst = matches!(ty, Ty::Slice(_, false, _));
                        let cst = if cst { "const " } else { "" };
                        self.line(&format!("{cst}{} *{nm}_p = {p};", c_ty(&ty)));
                        self.line(&format!("int64_t {nm}_n = {n};"));
                    }
                }
            }
            Stmt::LetArray(id, elems) => {
                let nm = self.local_name(*id);
                let ty = self.f.unwrap().locals[*id].ty.clone();
                let vals: Vec<String> = elems.iter().map(|e| self.expr(e).scalar()).collect();
                self.line(&format!("{} {nm}_buf[{}] = {{{}}};", c_ty(&ty), vals.len(), vals.join(", ")));
                self.line(&format!("{} *{nm}_p = {nm}_buf;", c_ty(&ty)));
                self.line(&format!("int64_t {nm}_n = {};", vals.len()));
            }
            Stmt::LetBuild { id, len, var, body } => {
                let nm = self.local_name(*id);
                let ty = self.f.unwrap().locals[*id].ty.clone();
                let cty = c_ty(&ty);
                let nv = self.expr(len).scalar();
                let k = self.local_name(*var);
                self.line(&format!("int64_t {nm}_n = {nv};"));
                self.line(&format!("{cty} *{nm}_p = nt_alloc({nm}_n, sizeof({cty}));"));
                self.line(&format!("for (int64_t {k} = 0; {k} < {nm}_n; {k}++) {{"));
                self.indent += 1;
                self.block_body(body, Target::Assign(format!("{nm}_p[{k}]")));
                self.indent -= 1;
                self.line("}");
            }
            Stmt::LetRepeat(id, e, n) => {
                let nm = self.local_name(*id);
                let ty = self.f.unwrap().locals[*id].ty.clone();
                let cty = c_ty(&ty);
                let nv = self.expr(n).scalar();
                self.line(&format!("int64_t {nm}_n = {nv};"));
                self.line(&format!("{cty} *{nm}_p = nt_alloc({nm}_n, sizeof({cty}));"));
                let v = self.expr(e).scalar();
                let k = self.fresh("k");
                self.line(&format!("{{ {cty} {k}v = {v}; for (int64_t {k} = 0; {k} < {nm}_n; {k}++) {nm}_p[{k}] = {k}v; }}"));
            }
            Stmt::Assign(lv, op, e) => {
                let v = self.expr(e).scalar();
                let opstr = op.map_or("".to_string(), |o| o.c_str().to_string());
                match lv {
                    LValue::Var(id) => {
                        let nm = self.local_name(*id);
                        self.line(&format!("{nm} {opstr}= {v};"));
                    }
                    LValue::Index(id, idx, line) => {
                        let nm = self.local_name(*id);
                        let i = self.expr(idx).scalar();
                        self.line(&format!("{nm}_p[nt_idx({i}, {nm}_n, {line})] {opstr}= {v};"));
                    }
                }
            }
            Stmt::For { var, start, end, body } => {
                let i = self.local_name(*var);
                let s = self.expr(start).scalar();
                let e = self.expr(end).scalar();
                let hi = self.fresh("end");
                self.line(&format!("for (int64_t {i} = {s}, {hi} = {e}; {i} < {hi}; {i}++) {{"));
                self.indent += 1;
                self.block_body(body, Target::Discard);
                self.indent -= 1;
                self.line("}");
            }
            Stmt::Expr(e) => self.expr_stmt(e),
            Stmt::Return(None) => self.line("return;"),
            Stmt::Return(Some(e)) => {
                let v = self.expr(e).scalar();
                self.line(&format!("return {v};"));
            }
        }
    }

    /// An expression in statement position: `if` and blocks become C statements, not statement
    /// expressions, so the common case reads like the source.
    fn expr_stmt(&mut self, e: &Expr) {
        match &e.kind {
            ExprKind::If(c, t, els) => {
                let cv = self.expr(c).scalar();
                self.line(&format!("if ({cv}) {{"));
                self.indent += 1;
                self.block_body(t, Target::Discard);
                self.indent -= 1;
                if let Some(b) = els {
                    self.line("} else {");
                    self.indent += 1;
                    self.block_body(b, Target::Discard);
                    self.indent -= 1;
                }
                self.line("}");
            }
            ExprKind::Block(b) => {
                self.line("{");
                self.indent += 1;
                self.block_body(b, Target::Discard);
                self.indent -= 1;
                self.line("}");
            }
            _ => {
                let v = self.expr(e).scalar();
                if e.ty == Ty::Unit {
                    self.line(&format!("{v};"));
                } else {
                    self.line(&format!("(void)({v});"));
                }
            }
        }
    }

    fn expr(&mut self, e: &Expr) -> CVal {
        let s = |v: String| CVal::Scalar(v);
        match &e.kind {
            ExprKind::Int(v) => {
                if *v == i64::MIN { s("INT64_MIN".to_string()) } else { s(format!("INT64_C({v})")) }
            }
            ExprKind::Float(v) => s(format!("{v:?}")),
            ExprKind::Bool(v) => s(if *v { "true".into() } else { "false".into() }),
            ExprKind::Local(id) => {
                let nm = self.local_name(*id);
                if self.f.unwrap().locals[*id].ty.is_arrayish() {
                    CVal::Arr(format!("{nm}_p"), format!("{nm}_n"))
                } else {
                    s(nm)
                }
            }
            ExprKind::Binary(op, a, b) => {
                let av = self.expr(a).scalar();
                let bv = self.expr(b).scalar();
                s(format!("({av} {} {bv})", op.c_str()))
            }
            ExprKind::Unary(op, a) => {
                let av = self.expr(a).scalar();
                s(match op { UnOp::Neg => format!("(-{av})"), UnOp::Not => format!("(!{av})") })
            }
            ExprKind::Index(id, idx) => {
                let nm = self.local_name(*id);
                let i = self.expr(idx).scalar();
                s(format!("{nm}_p[nt_idx({i}, {nm}_n, {})]", e.line))
            }
            ExprKind::Len(id) => s(format!("{}_n", self.local_name(*id))),
            ExprKind::Ref(id, _) => {
                let nm = self.local_name(*id);
                CVal::Arr(format!("{nm}_p"), format!("{nm}_n"))
            }
            ExprKind::Call(fid, args) => {
                let callee = &self.m.funcs[*fid];
                let mut parts = Vec::new();
                for a in args {
                    match self.expr(a) {
                        CVal::Scalar(v) => parts.push(v),
                        CVal::Arr(p, n) => { parts.push(p); parts.push(n); }
                    }
                }
                s(format!("nt_{}({})", callee.name, parts.join(", ")))
            }
            ExprKind::Println(a) => {
                let f = match a.ty { Ty::I64 => "nt_println_i64", Ty::F64 => "nt_println_f64", _ => "nt_println_bool" };
                let v = self.expr(a).scalar();
                s(format!("{f}({v})"))
            }
            ExprKind::Cast(a, ty) => {
                let v = self.expr(a).scalar();
                s(format!("(({})({v}))", c_ty(ty)))
            }
            ExprKind::MinMax(is_min, a, b) => {
                let (av, bv) = (self.expr(a).scalar(), self.expr(b).scalar());
                let t = c_ty(&e.ty);
                let op = if *is_min { "<" } else { ">" };
                let x = self.fresh("m");
                s(format!("({{ {t} {x}a = {av}, {x}b = {bv}; {x}a {op} {x}b ? {x}a : {x}b; }})"))
            }
            ExprKind::If(c, t, els) => {
                let cv = self.expr(c).scalar();
                let Some(eb) = els else {
                    // unit-typed, in expression position
                    return s(self.stmt_expr(|this| {
                        this.line(&format!("if ({cv}) {{"));
                        this.indent += 1;
                        this.block_body(t, Target::Discard);
                        this.indent -= 1;
                        this.line("}");
                    }));
                };
                // both branches plain values: a conditional expression
                if t.stmts.is_empty() && eb.stmts.is_empty() && t.tail.is_some() && eb.tail.is_some() && e.ty != Ty::Unit {
                    let tv = self.expr(t.tail.as_ref().unwrap()).scalar();
                    let ev = self.expr(eb.tail.as_ref().unwrap()).scalar();
                    return s(format!("({cv} ? {tv} : {ev})"));
                }
                let ty = e.ty.clone();
                let r = self.fresh("r");
                let rc = r.clone();
                s(self.stmt_expr(|this| {
                    let target = if ty == Ty::Unit { Target::Discard } else {
                        this.line(&format!("{} {rc};", c_ty(&ty)));
                        Target::Assign(rc.clone())
                    };
                    this.line(&format!("if ({cv}) {{"));
                    this.indent += 1;
                    this.block_body(t, target.clone());
                    this.indent -= 1;
                    this.line("} else {");
                    this.indent += 1;
                    this.block_body(eb, target);
                    this.indent -= 1;
                    this.line("}");
                    if ty != Ty::Unit { this.line(&format!("{rc};")); }
                }))
            }
            ExprKind::Block(b) => {
                let ty = e.ty.clone();
                let r = self.fresh("r");
                let rc = r.clone();
                s(self.stmt_expr(|this| {
                    if ty == Ty::Unit {
                        this.block_body(b, Target::Discard);
                    } else {
                        this.line(&format!("{} {rc};", c_ty(&ty)));
                        this.block_body(b, Target::Assign(rc.clone()));
                        this.line(&format!("{rc};"));
                    }
                }))
            }
        }
    }

    /// Run `body` with output redirected, and wrap what it wrote as `({ ... })`.
    fn stmt_expr(&mut self, body: impl FnOnce(&mut Self)) -> String {
        let saved = std::mem::take(&mut self.out);
        let saved_indent = self.indent;
        self.indent += 1;
        body(self);
        self.indent = saved_indent;
        let inner = std::mem::replace(&mut self.out, saved);
        let pad = "    ".repeat(saved_indent);
        format!("({{\n{inner}{pad}}})")
    }
}

#[derive(Clone)]
enum Target {
    Return,
    Assign(String),
    Discard,
}
