//! Typed IR → C. Every array or view is two C variables, `name_p` and `name_n`, so a parameter
//! can carry `restrict` on the pointer and the C compiler sees what the language already knows:
//! nothing aliases. Blocks and `if` with values use GNU statement expressions, which gcc and
//! clang — the two compilers this targets — both accept.

use std::fmt::Write;

use crate::ast::UnOp;
use crate::ir::*;

pub struct Options {
    /// Emit a bounds check on every index. Off for measurement.
    pub checked: bool,
}

enum CVal {
    Scalar(String),
    Arr(String, String),
    /// A struct array laid out one array per field: a pointer each, and the length.
    Soa(Vec<String>, String),
}

impl CVal {
    fn scalar(self) -> String {
        match self { CVal::Scalar(s) => s, CVal::Arr(p, _) => p, CVal::Soa(ps, _) => ps.into_iter().next().unwrap_or_default() }
    }
    /// The C arguments this value becomes at a call, and the parts a `let` binds.
    fn parts(self) -> Vec<String> {
        match self { CVal::Scalar(s) => vec![s], CVal::Arr(p, n) => vec![p, n], CVal::Soa(ps, n) => ps.into_iter().chain(std::iter::once(n)).collect() }
    }
}

struct Emitter<'a> {
    m: &'a Module,
    f: Option<&'a Func>,
    opts: &'a Options,
    out: String,
    indent: usize,
    tmp: usize,
    /// array locals of the function being emitted whose buffer may leave it — returned, or moved
    /// into something returned: a literal among them is built on the heap, not the stack
    escaping: std::collections::HashSet<LocalId>,
}

pub fn emit(m: &Module, opts: &Options) -> String {
    let mut e = Emitter { m, f: None, opts, out: String::new(), indent: 0, tmp: 0, escaping: Default::default() };
    e.prelude();
    e.structs();
    e.arr_returns();
    for f in &m.funcs {
        e.f = Some(f);
        e.prototype(f);
        e.out.push_str(";\n");
    }
    e.out.push('\n');
    for f in &m.funcs {
        e.f = Some(f);
        e.func(f);
    }
    // a program that reads its arguments hands them to `rt.c` first; any other keeps `main(void)`
    if m.funcs.iter().any(|f| crate::input::is_builtin(f) && f.name.starts_with("arg")) {
        e.out.push_str("void nt_set_args(int argc, char **argv);\nint main(int argc, char **argv) { nt_set_args(argc, argv); ntu_main(); return 0; }\n");
    } else {
        e.out.push_str("int main(void) { ntu_main(); return 0; }\n");
    }
    e.out
}

/// The C type a function returns: a scalar, `void`, or the pointer-and-length struct of an
/// owned array.
fn c_ret(m: &Module, t: &Ty) -> String {
    match t { Ty::Array(e, _) => format!("struct nt_arr_{}", c_ty(m, e).replace(' ', "_")), t => c_ty(m, t) }
}

fn c_ty(m: &Module, t: &Ty) -> String {
    match t {
        Ty::I64 => "int64_t".into(),
        Ty::F64 => "double".into(),
        Ty::Bool => "bool".into(),
        Ty::U8 => "uint8_t".into(),
        Ty::Unit => "void".into(),
        Ty::Struct(i) => format!("struct nt_{}", m.structs[*i].name),
        Ty::Array(e, _) | Ty::Slice(e, _, _) => c_ty(m, e),
    }
}

impl<'a> Emitter<'a> {
    fn prelude(&mut self) {
        self.out.push_str(r#"// generated by neant (bootstrap compiler)
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>

static void *nt_alloc(int64_t n, size_t sz) {
    if (n < 0) { fprintf(stderr, "negative array length %lld\n", (long long)n); exit(101); }
    void *p = malloc(n == 0 ? 1 : (size_t)n * sz);
    if (!p) { fprintf(stderr, "out of memory\n"); exit(101); }
    return p;
}
"#);
        if self.opts.checked {
            self.out.push_str(r#"static inline int64_t nt_idx(int64_t i, int64_t n, int line) {
    if ((uint64_t)i >= (uint64_t)n) {
        fprintf(stderr, "index %lld out of bounds for length %lld (line %d)\n", (long long)i, (long long)n, line);
        exit(101);
    }
    return i;
}
"#);
        } else {
            self.out.push_str("#define nt_idx(i, n, line) (i)\n");
        }
        self.out.push_str(r#"static void nt_println_i64(int64_t v) { printf("%lld\n", (long long)v); }
static void nt_println_bool(bool v) { puts(v ? "true" : "false"); }
static void nt_println_u8(uint8_t v) { printf("%u\n", (unsigned)v); }
static void nt_println_f64(double v) {
    // as Rust prints: shortest digits that round-trip, never an exponent, `.0` on integral values
    char buf[400];
    if (v != v) { puts("NaN"); return; }
    if (v == 1.0 / 0.0) { puts("inf"); return; }
    if (v == -1.0 / 0.0) { puts("-inf"); return; }
    int prec = 0;
    for (; prec < 17; prec++) {
        snprintf(buf, sizeof buf, "%.*e", prec, v);
        if (strtod(buf, NULL) == v) break;
    }
    int exp10 = atoi(strchr(buf, 'e') + 1);
    int decimals = prec - exp10;
    if (decimals < 0) decimals = 0;
    snprintf(buf, sizeof buf, "%.*f", decimals, v);
    if (!strchr(buf, '.')) strcat(buf, ".0");
    puts(buf);
}

"#);
    }

    /// One C struct per element type returned as an owned array: the pointer and the length,
    /// which is what an array is in this compiler.
    fn arr_returns(&mut self) {
        let mut seen: Vec<String> = Vec::new();
        for f in &self.m.funcs {
            let Ty::Array(e, _) = &f.ret else { continue };
            let c = c_ty(self.m, e);
            if seen.contains(&c) { continue; }
            seen.push(c.clone());
            let _ = writeln!(self.out, "struct nt_arr_{} {{ {c} *p; int64_t n; }};", c.replace(' ', "_"));
        }
        if !seen.is_empty() { self.out.push('\n'); }
    }

    /// One C struct per struct type, in declaration order; fields in declaration order, so the
    /// layout is C's and `Module::size_of` describes it.
    fn structs(&mut self) {
        for sd in &self.m.structs {
            let _ = writeln!(self.out, "struct nt_{} {{", sd.name);
            for (f, t) in &sd.fields {
                match t {
                    Ty::Array(_, Size::Const(k)) => { let _ = writeln!(self.out, "    {} {f}[{k}];", c_ty(self.m, t)); }
                    _ => { let _ = writeln!(self.out, "    {} {f};", c_ty(self.m, t)); }
                }
            }
            self.out.push_str("};\n");
        }
        if !self.m.structs.is_empty() { self.out.push('\n'); }
    }

    /// The fields of a struct array laid out one array per field, or `None` for anything else.
    fn soa_of(&self, t: &Ty) -> Option<&'a [(String, Ty)]> {
        match t.elem() {
            Some(Ty::Struct(i)) if self.m.structs[*i].layout == Layout::Soa => Some(&self.m.structs[*i].fields),
            _ => None,
        }
    }
    /// The C declarations for an array-valued name: `(type, name)` pairs, pointers then length.
    fn arr_decls(&self, nm: &str, t: &Ty, cst: bool) -> Vec<(String, String)> {
        let c = if cst { "const " } else { "" };
        match self.soa_of(t) {
            Some(fields) => fields.iter().map(|(f, ft)| (format!("{c}{} *", c_ty(self.m, ft)), format!("{nm}_{f}_p"))).collect(),
            None => vec![(format!("{c}{} *", c_ty(self.m, t)), format!("{nm}_p"))],
        }
    }
    /// The value of an array-valued local: its pointers and its length.
    fn arr_val(&self, nm: &str, t: &Ty) -> CVal {
        match self.soa_of(t) {
            Some(fields) => CVal::Soa(fields.iter().map(|(f, _)| format!("{nm}_{f}_p")).collect(), format!("{nm}_n")),
            None => CVal::Arr(format!("{nm}_p"), format!("{nm}_n")),
        }
    }

    fn local_name(&self, id: LocalId) -> String {
        let l = &self.f.unwrap().locals[id];
        // compiler-made locals are `base#n`; the id suffix already makes every name unique
        format!("{}_{}", l.name.replace('#', "_"), id)
    }

    fn prototype(&mut self, f: &Func) {
        let ret = c_ret(self.m, &f.ret);
        // an extern names the C symbol itself; our own functions are prefixed and static. The
        // prefix is `ntu_`, not `nt_`, so a function named `alloc` or `idx` cannot land on one of
        // this file's own runtime helpers (`nt_alloc`, `nt_idx`, `nt_println_*`) or on a generated
        // temporary (`nt_end2`) — found by the self-hosted parser, which has an `alloc`
        // an input builtin is `nt_` in `rt.c`, so it cannot meet a program's own extern of that
        // name — `rt.c`'s older `read_file(path, buf)` among them
        if crate::input::is_builtin(f) { let _ = write!(self.out, "{ret} nt_{}(", f.name); }
        else if f.body.is_none() { let _ = write!(self.out, "{ret} {}(", f.name); }
        else { let _ = write!(self.out, "static {ret} ntu_{}(", f.name); }
        if f.params.is_empty() {
            self.out.push_str("void");
        }
        for (i, &p) in f.params.iter().enumerate() {
            if i > 0 { self.out.push_str(", "); }
            let l = &f.locals[p];
            let nm = self.local_name(p);
            match &l.ty {
                // a `[T; k]` parameter is a buffer moved in: the callee's own, to write or return
                Ty::Slice(_, _, _) | Ty::Array(..) => {
                    let decls = self.arr_decls(&nm, &l.ty, matches!(l.ty, Ty::Slice(_, false, _)));
                    for (ty, name) in &decls { let _ = write!(self.out, "{ty}restrict {name}, "); }
                    let _ = write!(self.out, "int64_t {nm}_n");
                }
                t => { let _ = write!(self.out, "{} {nm}", c_ty(self.m, t)); }
            }
        }
        self.out.push(')');
    }

    fn func(&mut self, f: &Func) {
        let Some(body) = &f.body else { return };
        self.prototype(f);
        self.out.push_str(" {\n");
        self.indent = 1;
        self.tmp = 0;
        self.escaping = escaping(f, body);
        let ret_scalar = f.ret != Ty::Unit;
        self.block_body(body, if ret_scalar { Target::Return } else { Target::Discard });
        self.out.push_str("}\n\n");
    }

    fn line(&mut self, s: &str) {
        for _ in 0..self.indent { self.out.push_str("    "); }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn fresh(&mut self, base: &str) -> String {
        self.tmp += 1;
        format!("nt_{base}{}", self.tmp)
    }

    fn block_body(&mut self, b: &Block, target: Target) {
        for s in &b.stmts {
            self.stmt(s);
        }
        if let Some(t) = &b.tail {
            match target {
                Target::Return => {
                    let v = self.ret_val(t);
                    self.line(&format!("return {v};"));
                }
                Target::Assign(ref name) => {
                    let v = self.expr(t).scalar();
                    self.line(&format!("{name} = {v};"));
                }
                Target::Discard => {
                    self.expr_stmt(t);
                }
            }
        }
    }

    fn stmt(&mut self, s: &Stmt) {
        match s {
            Stmt::Let(id, e) => {
                let nm = self.local_name(*id);
                let ty = self.f.unwrap().locals[*id].ty.clone();
                if matches!(ty, Ty::Array(..)) && matches!(e.kind, ExprKind::Call(..)) {
                    let v = self.expr(e).scalar();
                    let t = self.fresh("a");
                    self.line(&format!("{} {t} = {v};", c_ret(self.m, &ty)));
                    self.line(&format!("{} *{nm}_p = {t}.p;", c_ty(self.m, &ty)));
                    self.line(&format!("int64_t {nm}_n = {t}.n;"));
                    return;
                }
                match self.expr(e) {
                    CVal::Scalar(v) => self.line(&format!("{} {nm} = {v};", c_ty(self.m, &ty))),
                    v => {
                        let parts = v.parts();
                        let cst = matches!(ty, Ty::Slice(_, false, _));
                        let decls = self.arr_decls(&nm, &ty, cst);
                        for ((dty, dnm), val) in decls.iter().zip(&parts) { self.line(&format!("{dty}{dnm} = {val};")); }
                        self.line(&format!("int64_t {nm}_n = {};", parts.last().unwrap()));
                    }
                }
            }
            Stmt::Reassign(idx) => {
                let r = self.f.unwrap().reassigns[*idx].clone();
                let ynm = self.local_name(r.target);
                let xnm = self.local_name(r.src);
                let ty = self.f.unwrap().locals[r.target].ty.clone();
                let fields: Vec<String> = match self.soa_of(&ty) {
                    Some(fs) => fs.iter().map(|(f, _)| format!("_{f}")).collect(),
                    None => vec![String::new()],
                };
                if r.in_place {
                    for suf in &fields { self.line(&format!("{ynm}{suf}_p = {xnm}{suf}_p;")); }
                } else {
                    let k = self.fresh("k");
                    self.line(&format!("for (int64_t {k} = 0; {k} < {xnm}_n; {k}++) {{"));
                    self.indent += 1;
                    for suf in &fields { self.line(&format!("{ynm}{suf}_p[{k}] = {xnm}{suf}_p[{k}];")); }
                    self.indent -= 1;
                    self.line("}");
                }
                self.line(&format!("{ynm}_n = {xnm}_n;"));
            }
            Stmt::LetArray(id, elems) => {
                let nm = self.local_name(*id);
                let ty = self.f.unwrap().locals[*id].ty.clone();
                let n = elems.len();
                match self.soa_of(&ty).map(|f| f.to_vec()) {
                    Some(fields) => {
                        let vals: Vec<String> = elems.iter().map(|e| self.expr(e).scalar()).collect();
                        for (k, (f, ft)) in fields.iter().enumerate() {
                            let parts: Vec<String> = vals.iter().map(|v| format!("({v}).{f}")).collect();
                            self.line(&format!("{} {nm}_{f}_buf[{n}] = {{{}}};", c_ty(self.m, ft), parts.join(", ")));
                            self.line(&format!("{} *{nm}_{f}_p = {nm}_{f}_buf;", c_ty(self.m, ft)));
                            let _ = k;
                        }
                    }
                    // a literal whose buffer leaves the function: the stack frame would not outlive it
                    None if self.escaping.contains(id) => {
                        let vals: Vec<String> = elems.iter().map(|e| self.expr(e).scalar()).collect();
                        let c = c_ty(self.m, &ty);
                        self.line(&format!("{c} *{nm}_p = nt_alloc({n}, sizeof({c}));"));
                        for (k, v) in vals.iter().enumerate() { self.line(&format!("{nm}_p[{k}] = {v};")); }
                    }
                    None => {
                        let vals: Vec<String> = elems.iter().map(|e| self.expr(e).scalar()).collect();
                        self.line(&format!("{} {nm}_buf[{n}] = {{{}}};", c_ty(self.m, &ty), vals.join(", ")));
                        self.line(&format!("{} *{nm}_p = {nm}_buf;", c_ty(self.m, &ty)));
                    }
                }
                self.line(&format!("int64_t {nm}_n = {n};"));
            }
            Stmt::LetBuild { id, len, var, body } => {
                let nm = self.local_name(*id);
                let ty = self.f.unwrap().locals[*id].ty.clone();
                let nv = self.expr(len).scalar();
                let k = self.local_name(*var);
                self.line(&format!("int64_t {nm}_n = {nv};"));
                self.alloc(&nm, &ty);
                self.line(&format!("for (int64_t {k} = 0; {k} < {nm}_n; {k}++) {{"));
                self.indent += 1;
                match self.soa_of(&ty).map(|f| f.to_vec()) {
                    Some(fields) => {
                        let tmp = self.fresh("e");
                        self.line(&format!("{} {tmp};", c_ty(self.m, ty.elem().unwrap())));
                        self.block_body(body, Target::Assign(tmp.clone()));
                        for (f, _) in &fields { self.line(&format!("{nm}_{f}_p[{k}] = {tmp}.{f};")); }
                    }
                    None => self.block_body(body, Target::Assign(format!("{nm}_p[{k}]"))),
                }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::LetRepeat(id, e, n) => {
                let nm = self.local_name(*id);
                let ty = self.f.unwrap().locals[*id].ty.clone();
                let cty = c_ty(self.m, ty.elem().unwrap_or(&ty));
                let nv = self.expr(n).scalar();
                self.line(&format!("int64_t {nm}_n = {nv};"));
                self.alloc(&nm, &ty);
                let v = self.expr(e).scalar();
                let k = self.fresh("k");
                let stores = match self.soa_of(&ty).map(|f| f.to_vec()) {
                    Some(fields) => fields.iter().map(|(f, _)| format!("{nm}_{f}_p[{k}] = {k}v.{f};")).collect::<Vec<_>>().join(" "),
                    None => format!("{nm}_p[{k}] = {k}v;"),
                };
                self.line(&format!("{{ {cty} {k}v = {v}; for (int64_t {k} = 0; {k} < {nm}_n; {k}++) {{ {stores} }} }}"));
            }
            // `s = f(…)`, `f -> [T; k]`: the local takes the returned buffer
            Stmt::Assign(LValue::Var(id), None, e) if matches!(self.f.unwrap().locals[*id].ty, Ty::Array(..)) => {
                let nm = self.local_name(*id);
                let ty = self.f.unwrap().locals[*id].ty.clone();
                let v = self.expr(e).scalar();
                let t = self.fresh("a");
                self.line(&format!("{{ {} {t} = {v}; {nm}_p = {t}.p; {nm}_n = {t}.n; }}", c_ret(self.m, &ty)));
            }
            Stmt::Assign(lv, op, e) => {
                let v = self.expr(e).scalar();
                let opstr = op.map_or("".to_string(), |o| o.c_str().to_string());
                match lv {
                    LValue::Var(id) => {
                        let nm = self.local_name(*id);
                        self.line(&format!("{nm} {opstr}= {v};"));
                    }
                    LValue::Index(id, idx, line) => {
                        let nm = self.local_name(*id);
                        let ty = self.f.unwrap().locals[*id].ty.clone();
                        let i = self.expr(idx).scalar();
                        match self.soa_of(&ty).map(|f| f.to_vec()) {
                            // a whole element under SoA is scattered into the field arrays
                            Some(fields) => {
                                let k = self.fresh("s");
                                self.line(&format!("{{ int64_t {k} = nt_idx({i}, {nm}_n, {line}); {} {k}v = {v};", c_ty(self.m, ty.elem().unwrap())));
                                for (f, _) in &fields { self.line(&format!("    {nm}_{f}_p[{k}] {opstr}= {k}v.{f};")); }
                                self.line("}");
                            }
                            None => self.line(&format!("{nm}_p[nt_idx({i}, {nm}_n, {line})] {opstr}= {v};")),
                        }
                    }
                    LValue::Field(id, fi) => {
                        let nm = self.local_name(*id);
                        let f = self.field_name(self.f.unwrap().locals[*id].ty.clone(), *fi);
                        self.line(&format!("{nm}.{f} {opstr}= {v};"));
                    }
                    LValue::FieldIndex(id, idx, fi, line) => {
                        let nm = self.local_name(*id);
                        let ty = self.f.unwrap().locals[*id].ty.clone();
                        let n = self.field_len(&ty, *fi);
                        let f = self.field_name(ty, *fi);
                        let i = self.expr(idx).scalar();
                        self.line(&format!("{nm}.{f}[nt_idx({i}, {n}, {line})] {opstr}= {v};"));
                    }
                    LValue::IndexField(id, idx, fi, line) => {
                        let nm = self.local_name(*id);
                        let ty = self.f.unwrap().locals[*id].ty.clone();
                        let i = self.expr(idx).scalar();
                        let f = self.field_name(ty.elem().unwrap().clone(), *fi);
                        if self.soa_of(&ty).is_some() {
                            self.line(&format!("{nm}_{f}_p[nt_idx({i}, {nm}_n, {line})] {opstr}= {v};"));
                        } else {
                            self.line(&format!("{nm}_p[nt_idx({i}, {nm}_n, {line})].{f} {opstr}= {v};"));
                        }
                    }
                    // an array of holders is AoS only (docs/arrays-by-value-design.md §9)
                    LValue::IndexFieldIndex(id, idx, fi, j, line) => {
                        let nm = self.local_name(*id);
                        let ty = self.f.unwrap().locals[*id].ty.clone();
                        let el = ty.elem().unwrap().clone();
                        let n = self.field_len(&el, *fi);
                        let f = self.field_name(el, *fi);
                        let i = self.expr(idx).scalar();
                        let jv = self.expr(j).scalar();
                        self.line(&format!("{nm}_p[nt_idx({i}, {nm}_n, {line})].{f}[nt_idx({jv}, {n}, {line})] {opstr}= {v};"));
                    }
                }
            }
            Stmt::For { var, start, end, body } => {
                let i = self.local_name(*var);
                let s = self.expr(start).scalar();
                let e = self.expr(end).scalar();
                let hi = self.fresh("end");
                self.line(&format!("for (int64_t {i} = {s}, {hi} = {e}; {i} < {hi}; {i}++) {{"));
                self.indent += 1;
                self.block_body(body, Target::Discard);
                self.indent -= 1;
                self.line("}");
            }
            Stmt::ParFor { var, end, body, acc, op } => {
                let i = self.local_name(*var);
                let e = self.expr(end).scalar();
                let hi = self.fresh("end");
                let accnm = self.local_name(*acc);
                let opstr = match op { ParOp::Add => "+", ParOp::Or => "||", ParOp::And => "&&" };
                // OpenMP's canonical loop form allows exactly one declarator in the init-clause,
                // so the end bound is hoisted out, unlike the sequential `for`'s `i = 0, end = e`
                self.line(&format!("int64_t {hi} = {e};"));
                self.line(&format!("#pragma omp parallel for reduction({opstr}:{accnm})"));
                self.line(&format!("for (int64_t {i} = 0; {i} < {hi}; {i}++) {{"));
                self.indent += 1;
                self.block_body(body, Target::Discard);
                self.indent -= 1;
                self.line("}");
            }
            Stmt::While { cond, body, .. } => {
                let c = self.expr(cond).scalar();
                self.line(&format!("while ({c}) {{"));
                self.indent += 1;
                self.block_body(body, Target::Discard);
                self.indent -= 1;
                self.line("}");
            }
            Stmt::Break => self.line("break;"),
            Stmt::Expr(e) => self.expr_stmt(e),
            Stmt::Return(None) => self.line("return;"),
            Stmt::Return(Some(e)) => {
                let v = self.ret_val(e);
                self.line(&format!("return {v};"));
            }
        }
    }

    /// An expression in statement position: `if` and blocks become C statements, not statement
    /// expressions, so the common case reads like the source.
    fn expr_stmt(&mut self, e: &Expr) {
        match &e.kind {
            ExprKind::If(c, t, els) => {
                let cv = self.expr(c).scalar();
                self.line(&format!("if ({cv}) {{"));
                self.indent += 1;
                self.block_body(t, Target::Discard);
                self.indent -= 1;
                if let Some(b) = els {
                    self.line("} else {");
                    self.indent += 1;
                    self.block_body(b, Target::Discard);
                    self.indent -= 1;
                }
                self.line("}");
            }
            ExprKind::Block(b) => {
                self.line("{");
                self.indent += 1;
                self.block_body(b, Target::Discard);
                self.indent -= 1;
                self.line("}");
            }
            _ => {
                let v = self.expr(e).scalar();
                if e.ty == Ty::Unit {
                    self.line(&format!("{v};"));
                } else {
                    self.line(&format!("(void)({v});"));
                }
            }
        }
    }

    fn expr(&mut self, e: &Expr) -> CVal {
        let s = |v: String| CVal::Scalar(v);
        match &e.kind {
            ExprKind::Int(v) => {
                if *v == i64::MIN { s("INT64_MIN".to_string()) } else { s(format!("INT64_C({v})")) }
            }
            ExprKind::Float(v) => s(format!("{v:?}")),
            ExprKind::Bool(v) => s(if *v { "true".into() } else { "false".into() }),
            ExprKind::Byte(v) => s(format!("((uint8_t){v})")),
            ExprKind::Local(id) => {
                let nm = self.local_name(*id);
                let ty = self.f.unwrap().locals[*id].ty.clone();
                if ty.is_arrayish() { self.arr_val(&nm, &ty) } else { s(nm) }
            }
            // a whole value compared element by element, every element, so the cost has no
            // early exit (docs/arrays-by-value-design.md §8)
            ExprKind::Binary(op, a, b) if !a.ty.is_scalar() => {
                let neg = if matches!(op, crate::ast::BinOp::Ne) { "!" } else { "" };
                let r = self.fresh("eq");
                match &a.ty {
                    Ty::Array(_, Size::Const(k)) => {
                        let (CVal::Arr(ap, _), CVal::Arr(bp, _)) = (self.expr(a), self.expr(b)) else { unreachable!("arrays compared are variables") };
                        s(format!("({neg}({{ bool {r} = 1; for (int64_t {r}k = 0; {r}k < {k}; {r}k++) {r} &= ({ap}[{r}k] == {bp}[{r}k]); {r}; }}))"))
                    }
                    Ty::Struct(sid) => {
                        let (av, bv) = (self.expr(a).scalar(), self.expr(b).scalar());
                        let ct = c_ty(self.m, &a.ty);
                        let mut body = format!("{ct} {r}a = {av}, {r}b = {bv}; bool {r} = 1;");
                        for (f, ft) in &self.m.structs[*sid].fields {
                            match ft {
                                Ty::Array(_, Size::Const(k)) => body.push_str(&format!(" for (int64_t {r}k = 0; {r}k < {k}; {r}k++) {r} &= ({r}a.{f}[{r}k] == {r}b.{f}[{r}k]);")),
                                _ => body.push_str(&format!(" {r} &= ({r}a.{f} == {r}b.{f});")),
                            }
                        }
                        s(format!("({neg}({{ {body} {r}; }}))"))
                    }
                    t => unreachable!("`==` on `{t}`"),
                }
            }
            ExprKind::Binary(op, a, b) => {
                let av = self.expr(a).scalar();
                let bv = self.expr(b).scalar();
                if e.ty == Ty::U8 { s(format!("((uint8_t)({av} {} {bv}))", op.c_str())) }
                else { s(format!("({av} {} {bv})", op.c_str())) }
            }
            ExprKind::Unary(op, a) => {
                let av = self.expr(a).scalar();
                s(match op { UnOp::Neg => format!("(-{av})"), UnOp::Not => format!("(!{av})") })
            }
            ExprKind::Index(id, idx) => {
                let nm = self.local_name(*id);
                let ty = self.f.unwrap().locals[*id].ty.clone();
                let i = self.expr(idx).scalar();
                match self.soa_of(&ty).map(|f| f.to_vec()) {
                    // a whole element under SoA is gathered from the field arrays
                    Some(fields) => {
                        let k = self.fresh("g");
                        let parts: Vec<String> = fields.iter().map(|(f, _)| format!(".{f} = {nm}_{f}_p[{k}]")).collect();
                        s(format!("({{ int64_t {k} = nt_idx({i}, {nm}_n, {}); ({}){{{}}}; }})", e.line, c_ty(self.m, ty.elem().unwrap()), parts.join(", ")))
                    }
                    None => s(format!("{nm}_p[nt_idx({i}, {nm}_n, {})]", e.line)),
                }
            }
            ExprKind::Len(id) => s(format!("{}_n", self.local_name(*id))),
            ExprKind::Field(base, fi) => {
                let f = self.field_name(base.ty.clone(), *fi);
                // `xs[i].f` under SoA is one load from that field's array, not a gather
                if let ExprKind::Index(id, idx) = &base.kind {
                    let ty = self.f.unwrap().locals[*id].ty.clone();
                    if self.soa_of(&ty).is_some() {
                        let nm = self.local_name(*id);
                        let i = self.expr(idx).scalar();
                        return s(format!("{nm}_{f}_p[nt_idx({i}, {nm}_n, {})]", e.line));
                    }
                }
                let b = self.expr(base).scalar();
                s(format!("({b}).{f}"))
            }
            // an array field is a C array member: C's struct copy is the value's copy
            ExprKind::FieldIndex(base, idx, fi) => {
                let n = self.field_len(&base.ty, *fi);
                let f = self.field_name(base.ty.clone(), *fi);
                let b = self.expr(base).scalar();
                let i = self.expr(idx).scalar();
                s(format!("({b}).{f}[nt_idx({i}, {n}, {})]", e.line))
            }
            ExprKind::ArrayVal(vals) => {
                let parts: Vec<String> = vals.iter().map(|v| self.expr(v).scalar()).collect();
                s(format!("{{{}}}", parts.join(", ")))
            }
            ExprKind::StructLit(sid, vals) => {
                let parts: Vec<String> = self.m.structs[*sid].fields.iter().map(|(f, _)| f.clone())
                    .zip(vals.iter().map(|v| self.expr(v).scalar())).map(|(f, v)| format!(".{f} = {v}")).collect();
                s(format!("((struct nt_{}){{{}}})", self.m.structs[*sid].name, parts.join(", ")))
            }
            ExprKind::Ref(id, _) => {
                let nm = self.local_name(*id);
                let ty = self.f.unwrap().locals[*id].ty.clone();
                self.arr_val(&nm, &ty)
            }
            ExprKind::Call(fid, args) => {
                let callee = &self.m.funcs[*fid];
                let mut parts = Vec::new();
                for a in args { parts.extend(self.expr(a).parts()); }
                if crate::input::is_builtin(callee) { s(format!("nt_{}({})", callee.name, parts.join(", "))) }
                else if callee.body.is_none() { s(format!("{}({})", callee.name, parts.join(", "))) }
                else { s(format!("ntu_{}({})", callee.name, parts.join(", "))) }
            }
            ExprKind::Println(a) => {
                let f = match a.ty { Ty::I64 => "nt_println_i64", Ty::F64 => "nt_println_f64", Ty::U8 => "nt_println_u8", _ => "nt_println_bool" };
                let v = self.expr(a).scalar();
                s(format!("{f}({v})"))
            }
            ExprKind::Cast(a, ty) => {
                let v = self.expr(a).scalar();
                s(format!("(({})({v}))", c_ty(self.m, ty)))
            }
            ExprKind::MinMax(is_min, a, b) => {
                let (av, bv) = (self.expr(a).scalar(), self.expr(b).scalar());
                let t = c_ty(self.m, &e.ty);
                let op = if *is_min { "<" } else { ">" };
                let x = self.fresh("m");
                s(format!("({{ {t} {x}a = {av}, {x}b = {bv}; {x}a {op} {x}b ? {x}a : {x}b; }})"))
            }
            ExprKind::If(c, t, els) => {
                let cv = self.expr(c).scalar();
                let Some(eb) = els else {
                    // unit-typed, in expression position
                    return s(self.stmt_expr(|this| {
                        this.line(&format!("if ({cv}) {{"));
                        this.indent += 1;
                        this.block_body(t, Target::Discard);
                        this.indent -= 1;
                        this.line("}");
                    }));
                };
                // both branches plain values: a conditional expression
                if t.stmts.is_empty() && eb.stmts.is_empty() && t.tail.is_some() && eb.tail.is_some() && e.ty != Ty::Unit {
                    let tv = self.expr(t.tail.as_ref().unwrap()).scalar();
                    let ev = self.expr(eb.tail.as_ref().unwrap()).scalar();
                    return s(format!("({cv} ? {tv} : {ev})"));
                }
                let ty = e.ty.clone();
                let r = self.fresh("r");
                let rc = r.clone();
                s(self.stmt_expr(|this| {
                    let target = if ty == Ty::Unit { Target::Discard } else {
                        this.line(&format!("{} {rc};", c_ty(self.m, &ty)));
                        Target::Assign(rc.clone())
                    };
                    this.line(&format!("if ({cv}) {{"));
                    this.indent += 1;
                    this.block_body(t, target.clone());
                    this.indent -= 1;
                    this.line("} else {");
                    this.indent += 1;
                    this.block_body(eb, target);
                    this.indent -= 1;
                    this.line("}");
                    if ty != Ty::Unit { this.line(&format!("{rc};")); }
                }))
            }
            ExprKind::Block(b) => {
                let ty = e.ty.clone();
                let r = self.fresh("r");
                let rc = r.clone();
                s(self.stmt_expr(|this| {
                    if ty == Ty::Unit {
                        this.block_body(b, Target::Discard);
                    } else {
                        this.line(&format!("{} {rc};", c_ty(self.m, &ty)));
                        this.block_body(b, Target::Assign(rc.clone()));
                        this.line(&format!("{rc};"));
                    }
                }))
            }
        }
    }

    /// The C expression a `return` yields: an array becomes its pointer and length in a struct.
    fn ret_val(&mut self, e: &Expr) -> String {
        let ty = e.ty.clone();
        match self.expr(e) {
            CVal::Arr(p, n) => format!("(({}){{ .p = {p}, .n = {n} }})", c_ret(self.m, &ty)),
            v => v.scalar(),
        }
    }

    /// Allocate the buffers of an array local `nm` of type `ty`, whose `_n` is already declared.
    fn alloc(&mut self, nm: &str, ty: &Ty) {
        match self.soa_of(ty).map(|f| f.to_vec()) {
            Some(fields) => for (f, ft) in &fields {
                let c = c_ty(self.m, ft);
                self.line(&format!("{c} *{nm}_{f}_p = nt_alloc({nm}_n, sizeof({c}));"));
            },
            None => {
                let c = c_ty(self.m, ty.elem().unwrap_or(ty));
                self.line(&format!("{c} *{nm}_p = nt_alloc({nm}_n, sizeof({c}));"));
            }
        }
    }

    /// The C name of field `fi` of a struct type (or of a struct array's element type).
    /// The length of array field `fi` of struct type `t`.
    fn field_len(&self, t: &Ty, fi: usize) -> i64 {
        match t { Ty::Struct(i) => match &self.m.structs[*i].fields[fi].1 { Ty::Array(_, Size::Const(k)) => *k, _ => unreachable!("not an array field") }, _ => unreachable!("field of a non-struct") }
    }

    fn field_name(&self, t: Ty, fi: usize) -> String {
        let t = match t { Ty::Array(e, _) | Ty::Slice(e, _, _) => *e, t => t };
        match t { Ty::Struct(i) => self.m.structs[i].fields[fi].0.clone(), _ => unreachable!("field of a non-struct") }
    }

    /// Run `body` with output redirected, and wrap what it wrote as `({ ... })`.
    fn stmt_expr(&mut self, body: impl FnOnce(&mut Self)) -> String {
        let saved = std::mem::take(&mut self.out);
        let saved_indent = self.indent;
        self.indent += 1;
        body(self);
        self.indent = saved_indent;
        let inner = std::mem::replace(&mut self.out, saved);
        let pad = "    ".repeat(saved_indent);
        format!("({{\n{inner}{pad}}})")
    }
}

#[derive(Clone)]
enum Target {
    Return,
    Assign(String),
    Discard,
}

/// The array locals of `f` whose buffer may be returned: what a `return` or the tail names, what
/// a call it returns was handed by value, and back through every `let`, move and rebinding that
/// gave one of those its buffer.
fn escaping(f: &Func, body: &Block) -> std::collections::HashSet<LocalId> {
    fn names(e: &Expr, f: &Func, out: &mut Vec<LocalId>) {
        match &e.kind {
            ExprKind::Local(id) if matches!(f.locals[*id].ty, Ty::Array(..)) => out.push(*id),
            ExprKind::Call(_, args) if matches!(e.ty, Ty::Array(..)) => for a in args { names(a, f, out); },
            ExprKind::If(_, t, els) => for b in std::iter::once(t).chain(els.iter()) { if let Some(x) = &b.tail { names(x, f, out); } },
            ExprKind::Block(b) => if let Some(x) = &b.tail { names(x, f, out); },
            _ => {}
        }
    }
    // (destination, the locals whose buffer it may take); `None` for what is returned
    fn edges(b: &Block, f: &Func, out: &mut Vec<(Option<LocalId>, Vec<LocalId>)>) {
        for s in &b.stmts {
            match s {
                Stmt::Let(id, e) | Stmt::Assign(LValue::Var(id), None, e) => { let mut v = vec![]; names(e, f, &mut v); out.push((Some(*id), v)); }
                Stmt::Reassign(idx) => { let r = &f.reassigns[*idx]; out.push((Some(r.target), vec![r.src])); }
                Stmt::Return(Some(e)) => { let mut v = vec![]; names(e, f, &mut v); out.push((None, v)); }
                Stmt::For { body, .. } | Stmt::While { body, .. } | Stmt::ParFor { body, .. } => edges(body, f, out),
                Stmt::Expr(e) => expr_edges(e, f, out),
                _ => {}
            }
        }
        if let Some(t) = &b.tail { expr_edges(t, f, out); }
    }
    fn expr_edges(e: &Expr, f: &Func, out: &mut Vec<(Option<LocalId>, Vec<LocalId>)>) {
        match &e.kind {
            ExprKind::If(_, t, els) => { edges(t, f, out); if let Some(b) = els { edges(b, f, out); } }
            ExprKind::Block(b) => edges(b, f, out),
            _ => {}
        }
    }
    let mut es = Vec::new();
    edges(body, f, &mut es);
    let mut out = std::collections::HashSet::new();
    let mut tail = vec![];
    if let Some(t) = &body.tail { names(t, f, &mut tail); }
    out.extend(tail);
    loop {
        let before = out.len();
        for (dst, srcs) in &es {
            if dst.is_none_or(|d| out.contains(&d)) { out.extend(srcs.iter().copied()); }
        }
        if out.len() == before { return out; }
    }
}
